"""Telemetry service compatibility shim."""

from services.infra_facade import BUG_REPORT
from services.infra_facade import TELEMETRY
from services.infra_facade import bug_report_new_issue_url
from services.infra_facade import build_bug_report_markdown
from services.infra_facade import build_bug_screenshot_repo_path
from services.infra_facade import copy_bug_report_body_to_clipboard
from services.infra_facade import detect_bug_screenshot_magic_ext
from services.infra_facade import has_bug_report_token
from services.infra_facade import mark_submit_now
from services.infra_facade import open_bug_report_in_browser
from services.infra_facade import prepare_bug_screenshot_upload_bytes
from services.infra_facade import sanitize_bug_screenshot_slug
from services.infra_facade import submit_bug_report_discord_forum
from services.infra_facade import submit_cooldown_remaining
from services.infra_facade import trigger_report_flow
from services.infra_facade import upload_bug_screenshot
from services.infra_facade import validate_bug_screenshot_dimensions
from services.infra_facade import validate_bug_screenshot_file


bug_report_api_service = BUG_REPORT.bug_report_api_service
bug_report_browser_service = BUG_REPORT.bug_report_browser_service
bug_report_context_service = BUG_REPORT.bug_report_context_service
bug_report_cooldown_service = BUG_REPORT.bug_report_cooldown_service
bug_report_service = BUG_REPORT.bug_report_service
bug_report_submission_service = BUG_REPORT.bug_report_submission_service
bug_report_ui_service = BUG_REPORT.bug_report_ui_service
clipboard_service = BUG_REPORT.clipboard_service
crash_logging_service = BUG_REPORT.crash_logging_service
crash_offer_service = BUG_REPORT.crash_offer_service
crash_report_service = BUG_REPORT.crash_report_service
diag_log_housekeeping_service = BUG_REPORT.diag_log_housekeeping_service
error_hook_service = BUG_REPORT.error_hook_service
error_overlay_service = BUG_REPORT.error_overlay_service
error_service = BUG_REPORT.error_service
